services:
  neo4j:
    container_name: neo4j
    image: neo4j:latest
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=neo4j/${NEO4J_PASSWORD}
      - dbms.connector.bolt.listen_address=:7688
      - dbms.connector.bolt.advertised_address=:7688
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_PLUGINS=["apoc", "graph-data-science"]
    volumes:
      - ./neo4j_db/data:/data
      - ./neo4j_db/logs:/logs
      - ./neo4j_db/import:/var/lib/neo4j/import
      - ./neo4j_db/plugins:/plugins
  python-app:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn src.main:app --host 0.0.0.0
    ports:
      - "8000:8000"
    environment:
      - NEO4J_URL=bolt://neo4j:7687
      - NEO4J_USER=${NEO4J_USER}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD} 
      - OPENAI_API_VERSION=${OPENAI_API_VERSION}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - MEMORY_MAX_MESSAGES=${MEMORY_MAX_MESSAGES}
      - ASSISTANT_API_KEY=${ASSISTANT_API_KEY}
    depends_on:
      - neo4j
volumes:
  data:
  logs: